version: "3.8"
services:
  # --- DATABASES ---
  mysql-order:
    container_name: mysql-order
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_service
      MYSQL_USER: ibatulanand
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_order:/var/lib/mysql
    ports:
      - "3307:3306"

  mysql-inventory:
    container_name: mysql-inventory
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_service
      MYSQL_USER: ibatulanand
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_inventory:/var/lib/mysql
    ports:
      - "3308:3306"

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  # --- MESSAGING (Kafka KRaft Mode) ---
  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # Required for KRaft Mode:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  # --- TRACING ---
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    
  # --- MICROSERVICES ---
  product-service:
    container_name: product-service
    image: ibatulanandjp/product-service:latest
    platform: linux/amd64 
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/product-service
    depends_on:
      - mongo
      
  order-service:
    container_name: order-service
    image: ibatulanandjp/order-service:latest
    platform: linux/amd64
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order:3306/order_service
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
    depends_on:
      - mysql-order
      - broker

  inventory-service:
    container_name: inventory-service
    image: ibatulanandjp/inventory-service:latest
    platform: linux/amd64
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-inventory:3306/inventory_service
    depends_on:
      - mysql-inventory
      
  notification-service:
    container_name: notification-service
    image: ibatulanandjp/notification-service:latest
    platform: linux/amd64
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
    depends_on:
      - broker
